language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip install codecov

script:
  - pytest -s --cov=sqs_client

after_success:
  - codecov # submit coverage