services:
  localstack:
    image: localstack/localstack:stable
    container_name: sqs-extended-localstack
    ports:
      - "4566:4566"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: "0"
      GATEWAY_LISTEN: 0.0.0.0:4566
      SQS_EXTENDED_S3_BUCKET: sqs-extended-payloads
      SQS_EXTENDED_QUEUE_NAME: sqs-extended-demo
      SQS_EXTENDED_FIFO_QUEUE_NAME: sqs-extended-demo.fifo
    volumes:
      - ./docker/ready.d:/etc/localstack/init/ready.d
